In [31]:
import pandas as pd

aisles = pd.read_csv("../dataset/aisles.csv")
departments = pd.read_csv("../dataset/department.csv")
products = pd.read_csv("../dataset/products.csv.zip")
orders = pd.read_csv("../dataset/orders.csv.zip")
order_products_prior = pd.read_csv("../dataset/order_products__prior.csv.zip")

In [14]:
aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [16]:
departments.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [18]:
products.head()

,product_id,product_name,aisle_id,department_id
0,1,Chocolate Sandwich Cookies,61,19
1,2,All-Seasons Salt,104,13
2,3,Robust Golden Unsweetened Oolong Tea,94,7
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1
4,5,Green Chile Anytime Sauce,5,13

In [23]:
orders.head(10)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0
5,3367565,1,prior,6,2,7,19.0
6,550135,1,prior,7,1,9,20.0
7,3108588,1,prior,8,1,14,14.0
8,2295261,1,prior,9,1,16,0.0
9,2550362,1,prior,10,4,8,30.0

In [32]:
order_products_prior.head()

   order_id  product_id  add_to_cart_order  reordered
0         2       33120                  1          1
1         2       28985                  2          1
2         2        9327                  3          0
3         2       45918                  4          1
4         2       30035                  5          0

In [24]:
aisles.info()
# Aisle is the sections in a supermart eg:Pasta aisle

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   aisle_id  134 non-null    int64
 1   aisle     134 non-null    object
dtypes: int64(1), object(1)
memory usage: 2.2+ KB

In [26]:
departments.info()
#Department groups similar products together

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   department_id  21 non-null     int64
 1   department     21 non-null     object
dtypes: int64(1), object(1)
memory usage: 468.0+ bytes

In [28]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3421083 entries, 0 to 3421082
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   order_id                int64
 1   user_id                 int64
 2   eval_set                object
 3   order_number            int64
 4   order_dow               int64
 5   order_hour_of_day       int64
 6   days_since_prior_order  float64
dtypes: float64(1), int64(5), object(1)
memory usage: 182.7+ MB

In [27]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49688 entries, 0 to 49687
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     49688 non-null  int64
 1   product_name   49688 non-null  object
 2   aisle_id       49688 non-null  int64
 3   department_id  49688 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [34]:
order_products_prior.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32434489 entries, 0 to 32434488
Data columns (total 4 columns):
 #   Column             Dtype
---  ------             -----
 0   order_id           int64
 1   product_id         int64
 2   add_to_cart_order  int64
 3   reordered          int64
dtypes: int64(4)
memory usage: 989.8 MB

In [42]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:@localhost/instacart"
)

In [41]:
aisles.to_sql(
    "aisles",
    engine,
    if_exists="replace",
    index=False
)

134

In [39]:
departments.to_sql(
    "departments",
    engine,
    if_exists="replace",
    index=False
)

products.to_sql(
    "products",
    engine,
    if_exists="replace",
    index=False
)

orders.to_sql(
    "orders",
    engine,
    if_exists="replace",
    index=False,
    chunksize=50000
)

3421083

In [45]:
for start in range(0, len(order_products_prior), 5000):
    chunk = order_products_prior.iloc[start:start+5000]

    chunk.to_sql(
        "order_products_prior",
        engine,
        if_exists="append" if start > 0 else "replace",
        index=False,
        method="multi"
    )

    print(f"Inserted {start + len(chunk):,} rows")

Inserted 5,000 rows
Inserted 10,000 rows
Inserted 15,000 rows
Inserted 20,000 rows
Inserted 25,000 rows
Inserted 30,000 rows
Inserted 35,000 rows
Inserted 40,000 rows
Inserted 45,000 rows
Inserted 50,000 rows
Inserted 55,000 rows
Inserted 60,000 rows
Inserted 65,000 rows
Inserted 70,000 rows
Inserted 75,000 rows
Inserted 80,000 rows
Inserted 85,000 rows
Inserted 90,000 rows
Inserted 95,000 rows
Inserted 100,000 rows
Inserted 105,000 rows
Inserted 110,000 rows
Inserted 115,000 rows
Inserted 120,000 rows
Inserted 125,000 rows
Inserted 130,000 rows
Inserted 135,000 rows
Inserted 140,000 rows
Inserted 145,000 rows
Inserted 150,000 rows
Inserted 155,000 rows
Inserted 160,000 rows
Inserted 165,000 rows
Inserted 170,000 rows
Inserted 175,000 rows
Inserted 180,000 rows
Inserted 185,000 rows
Inserted 190,000 rows
Inserted 195,000 rows
Inserted 200,000 rows
Inserted 205,000 rows
Inserted 210,000 rows
Inserted 215,000 rows
Inserted 220,000 rows
Inserted 225,000 rows
Inserted 230,000 rows
Inserted 235,000 rows
Inserted 240,000 rows
Inserted 245,000 rows
Inserted 250,000 rows
Inserted 255,000 rows
Inserted 260,000 rows
Inserted 265,000 rows
Inserted 270,000 rows
Inserted 275,000 rows
Inserted 280,000 rows
Inserted 285,000 rows
Inserted 290,000 rows
Inserted 295,000 rows
Inserted 300,000 rows
Inserted 305,000 rows
Inserted 310,000 rows
Inserted 315,000 rows
Inserted 320,000 rows
Inserted 325,000 rows
Inserted 330,000 rows
Inserted 335,000 rows
Inserted 340,000 rows
Inserted 345,000 rows
Inserted 350,000 rows
Inserted 355,000 rows
Inserted 360,000 rows
Inserted 365,000 rows
Inserted 370,000 rows
Inserted 375,000 rows
Inserted 380,000 rows
Inserted 385,000 rows
Inserted 390,000 rows
Inserted 395,000 rows
Inserted 400,000 rows
Inserted 405,000 rows
Inserted 410,000 rows
Inserted 415,000 rows
Inserted 420,000 rows
Inserted 425,000 rows
Inserted 430,000 rows
Inserted 435,000 rows
Inserted 440,000 rows
Inserted 445,000 rows
Inserted 450,000 rows
Inserted 455,000 rows
Inserted 460,000 rows
Inserted 465,000 rows
Inserted 470,000 rows
Inserted 475,000 rows
Inserted 480,000 rows
Inserted 485,000 rows
Inserted 490,000 rows
Inserted 495,000 rows
Inserted 500,000 rows
Inserted 505,000 rows
Inserted 510,000 rows
Inserted 515,000 rows
Inserted 520,000 rows
Inserted 525,000 rows
Inserted 530,000 rows
Inserted 535,000 rows
Inserted 540,000 rows
Inserted 545,000 rows
Inserted 550,000 rows
Inserted 555,000 rows
Inserted 560,000 rows
Inserted 565,000 rows
Inserted 570,000 rows
Inserted 575,000 rows
Inserted 580,000 rows
Inserted 585,000 rows
Inserted 590,000 rows
Inserted 595,000 rows
Inserted 600,000 rows
Inserted 605,000 rows
Inserted 610,000 rows
Inserted 615,000 rows
Inserted 620,000 rows
Inserted 625,000 rows
Inserted 630,000 rows
Inserted 635,000 rows
Inserted 640,000 rows
Inserted 645,000 rows
Inserted 650,000 rows
Inserted 655,000 rows
Inserted 660,000 rows
Inserted 665,000 rows
Inserted 670,000 rows
Inserted 675,000 rows
Inserted 680,000 rows
Inserted 685,000 rows
Inserted 690,000 rows
Inserted 695,000 rows
Inserted 700,000 rows
Inserted 705,000 rows
Inserted 710,000 rows
Inserted 715,000 rows
Inserted 720,000 rows
Inserted 725,000 rows
Inserted 730,000 rows
Inserted 735,000 rows
Inserted 740,000 rows
Inserted 745,000 rows
Inserted 750,000 rows
Inserted 755,000 rows
Inserted 760,000 rows
Inserted 765,000 rows
Inserted 770,000 rows
Inserted 775,000 rows
Inserted 780,000 rows
Inserted 785,000 rows
Inserted 790,000 rows
Inserted 795,000 rows
Inserted 800,000 rows
Inserted 805,000 rows
Inserted 810,000 rows
Inserted 815,000 rows
Inserted 820,000 rows
Inserted 825,000 rows
Inserted 830,000 rows
Inserted 835,000 rows
Inserted 840,000 rows
Inserted 845,000 rows
Inserted 850,000 rows
Inserted 855,000 rows
Inserted 860,000 rows
Inserted 865,000 rows
Inserted 870,000 rows
Inserted 875,000 rows
Inserted 880,000 rows
Inserted 885,000 rows
Inserted 890,000 rows
Inserted 895,000 rows
Inserted 900,000 rows
Inserted 905,000 rows
Inserted 910,000 rows
Inserted 915,000 rows
Inserted 920,000 rows
Inserted 925,000 rows
Inserted 930,000 rows
Inserted 935,000 rows
Inserted 940,000 rows
Inserted 945,000 rows
Inserted 950,000 rows
Inserted 955,000 rows
Inserted 960,000 rows
Inserted 965,000 rows
Inserted 970,000 rows
Inserted 975,000 rows
Inserted 980,000 rows
Inserted 985,000 rows
Inserted 990,000 rows
Inserted 995,000 rows
Inserted 1,000,000 rows
Inserted 1,005,000 rows
Inserted 1,010,000 rows
Inserted 1,015,000 rows
Inserted 1,020,000 rows
Inserted 1,025,000 rows
Inserted 1,030,000 rows
Inserted 1,035,000 rows
Inserted 1,040,000 rows
Inserted 1,045,000 rows
Inserted 1,050,000 rows
Inserted 1,055,000 rows
Inserted 1,060,000 rows
Inserted 1,065,000 rows
Inserted 1,070,000 rows
Inserted 1,075,000 rows
Inserted 1,080,000 rows
Inserted 1,085,000 rows
Inserted 1,090,000 rows
Inserted 1,095,000 rows
Inserted 1,100,000 rows
Inserted 1,105,000 rows
Inserted 1,110,000 rows
Inserted 1,115,000 rows
Inserted 1,120,000 rows
Inserted 1,125,000 rows
Inserted 1,130,000 rows
Inserted 1,135,000 rows
Inserted 1,140,000 rows
Inserted 1,145,000 rows
Inserted 1,150,000 rows
Inserted 1,155,000 rows
Inserted 1,160,000 rows
Inserted 1,165,000 rows
Inserted 1,170,000 rows
Inserted 1,175,000 rows
Inserted 1,180,000 rows
Inserted 1,185,000 rows
Inserted 1,190,000 rows
Inserted 1,195,000 rows
Inserted 1,200,000 rows
Inserted 1,205,000 rows
Inserted 1,210,000 rows
Inserted 1,215,000 rows
Inserted 1,220,000 rows
Inserted 1,225,000 rows
Inserted 1,230,000 rows
Inserted 1,235,000 rows
Inserted 1,240,000 rows
Inserted 1,245,000 rows
Inserted 1,250,000 rows
Inserted 1,255,000 rows
Inserted 1,260,000 rows
Inserted 1,265,000 rows
Inserted 1,270,000 rows
Inserted 1,275,000 rows
Inserted 1,280,000 rows
Inserted 1,285,000 rows
Inserted 1,290,000 rows
Inserted 1,295,000 rows
Inserted 1,300,000 rows
Inserted 1,305,000 rows
Inserted 1,310,000 rows
Inserted 1,315,000 rows
Inserted 1,320,000 rows
Inserted 1,325,000 rows
Inserted 1,330,000 rows
Inserted 1,335,000 rows
Inserted 1,340,000 rows
Inserted 1,345,000 rows
Inserted 1,350,000 rows
Inserted 1,355,000 rows
Inserted 1,360,000 rows
Inserted 1,365,000 rows
Inserted 1,370,000 rows
Inserted 1,375,000 rows
Inserted 1,380,000 rows
Inserted 1,385,000 rows
Inserted 1,390,000 rows
Inserted 1,395,000 rows
Inserted 1,400,000 rows
Inserted 1,405,000 rows
Inserted 1,410,000 rows
Inserted 1,415,000 rows
Inserted 1,420,000 rows
Inserted 1,425,000 rows
Inserted 1,430,000 rows
Inserted 1,435,000 rows
Inserted 1,440,000 rows
Inserted 1,445,000 rows
Inserted 1,450,000 rows
Inserted 1,455,000 rows
Inserted 1,460,000 rows
Inserted 1,465,000 rows
Inserted 1,470,000 rows
Inserted 1,475,000 rows
Inserted 1,480,000 rows
Inserted 1,485,000 rows
Inserted 1,490,000 rows
Inserted 1,495,000 rows
Inserted 1,500,000 rows
Inserted 1,505,000 rows
Inserted 1,510,000 rows
Inserted 1,515,000 rows
Inserted 1,520,000 rows
Inserted 1,525,000 rows
Inserted 1,530,000 rows
Inserted 1,535,000 rows
Inserted 1,540,000 rows
Inserted 1,545,000 rows
Inserted 1,550,000 rows
Inserted 1,555,000 rows
Inserted 1,560,000 rows
Inserted 1,565,000 rows
Inserted 1,570,000 rows
Inserted 1,575,000 rows
Inserted 1,580,000 rows
Inserted 1,585,000 rows
Inserted 1,590,000 rows
Inserted 1,595,000 rows
Inserted 1,600,000 rows
Inserted 1,605,000 rows
Inserted 1,610,000 rows
Inserted 1,615,000 rows
Inserted 1,620,000 rows
Inserted 1,625,000 rows
Inserted 1,630,000 rows
Inserted 1,635,000 rows
Inserted 1,640,000 rows
Inserted 1,645,000 rows
Inserted 1,650,000 rows
Inserted 1,655,000 rows
Inserted 1,660,000 rows
Inserted 1,665,000 rows
Inserted 1,670,000 rows
Inserted 1,675,000 rows
Inserted 1,680,000 rows
Inserted 1,685,000 rows
Inserted 1,690,000 rows
Inserted 1,695,000 rows
Inserted 1,700,000 rows
Inserted 1,705,000 rows
Inserted 1,710,000 rows
Inserted 1,715,000 rows
Inserted 1,720,000 rows
Inserted 1,725,000 rows
Inserted 1,730,000 rows
Inserted 1,735,000 rows
Inserted 1,740,000 rows
Inserted 1,745,000 rows
Inserted 1,750,000 rows
Inserted 1,755,000 rows
Inserted 1,760,000 rows
Inserted 1,765,000 rows
Inserted 1,770,000 rows
Inserted 1,775,000 rows
Inserted 1,780,000 rows
Inserted 1,785,000 rows
Inserted 1,790,000 rows
Inserted 1,795,000 rows
Inserted 1,800,000 rows
Inserted 1,805,000 rows
Inserted 1,810,000 rows
Inserted 1,815,000 rows
Inserted 1,820,000 rows
Inserted 1,825,000 rows
Inserted 1,830,000 rows
Inserted 1,835,000 rows
Inserted 1,840,000 rows
Inserted 1,845,000 rows
Inserted 1,850,000 rows
Inserted 1,855,000 rows
Inserted 1,860,000 rows
Inserted 1,865,000 rows
Inserted 1,870,000 rows
Inserted 1,875,000 rows
Inserted 1,880,000 rows
Inserted 1,885,000 rows
Inserted 1,890,000 rows
Inserted 1,895,000 rows
Inserted 1,900,000 rows
Inserted 1,905,000 rows
Inserted 1,910,000 rows
Inserted 1,915,000 rows
Inserted 1,920,000 rows
Inserted 1,925,000 rows
Inserted 1,930,000 rows
Inserted 1,935,000 rows
Inserted 1,940,000 rows
Inserted 1,945,000 rows
Inserted 1,950,000 rows
Inserted 1,955,000 rows
Inserted 1,960,000 rows
Inserted 1,965,000 rows
Inserted 1,970,000 rows
Inserted 1,975,000 rows
Inserted 1,980,000 rows
Inserted 1,985,000 rows
Inserted 1,990,000 rows
Inserted 1,995,000 rows
Inserted 2,000,000 rows
Inserted 2,005,000 rows
Inserted 2,010,000 rows
Inserted 2,015,000 rows
Inserted 2,020,000 rows
Inserted 2,025,000 rows
Inserted 2,030,000 rows
Inserted 2,035,000 rows
Inserted 2,040,000 rows
Inserted 2,045,000 rows
Inserted 2,050,000 rows
Inserted 2,055,000 rows
Inserted 2,060,000 rows
Inserted 2,065,000 rows
Inserted 2,070,000 rows
Inserted 2,075,000 rows
Inserted 2,080,000 rows
Inserted 2,085,000 rows
Inserted 2,090,000 rows
Inserted 2,095,000 rows
Inserted 2,100,000 rows
Inserted 2,105,000 rows
Inserted 2,110,000 rows
Inserted 2,115,000 rows
Inserted 2,120,000 rows
Inserted 2,125,000 rows
Inserted 2,130,000 rows
Inserted 2,135,000 rows
Inserted 2,140,000 rows
Inserted 2,145,000 rows
Inserted 2,150,000 rows
Inserted 2,155,000 rows
Inserted 2,160,000 rows
Inserted 2,165,000 rows
Inserted 2,170,000 rows
Inserted 2,175,000 rows
Inserted 2,180,000 rows
Inserted 2,185,000 rows
Inserted 2,190,000 rows
Inserted 2,195,000 rows
Inserted 2,200,000 rows
Inserted 2,205,000 rows
Inserted 2,210,000 rows
Inserted 2,215,000 rows
Inserted 2,220,000 rows
Inserted 2,225,000 rows
Inserted 2,230,000 rows
Inserted 2,235,000 rows
Inserted 2,240,000 rows
Inserted 2,245,000 rows
Inserted 2,250,000 rows
Inserted 2,255,000 rows
Inserted 2,260,000 rows
Inserted 2,265,000 rows
Inserted 2,270,000 rows
Inserted 2,275,000 rows
Inserted 2,280,000 rows
Inserted 2,285,000 rows
Inserted 2,290,000 rows
Inserted 2,295,000 rows
Inserted 2,300,000 rows
Inserted 2,305,000 rows
Inserted 2,310,000 rows
Inserted 2,315,000 rows
Inserted 2,320,000 rows
Inserted 2,325,000 rows
Inserted 2,330,000 rows
Inserted 2,335,000 rows
Inserted 2,340,000 rows
Inserted 2,345,000 rows
Inserted 2,350,000 rows
Inserted 2,355,000 rows
Inserted 2,360,000 rows
Inserted 2,365,000 rows
Inserted 2,370,000 rows
Inserted 2,375,000 rows
Inserted 2,380,000 rows
Inserted 2,385,000 rows
Inserted 2,390,000 rows
Inserted 2,395,000 rows
Inserted 2,400,000 rows
Inserted 2,405,000 rows
Inserted 2,410,000 rows
Inserted 2,415,000 rows
Inserted 2,420,000 rows
Inserted 2,425,000 rows
Inserted 2,430,000 rows
Inserted 2,435,000 rows
Inserted 2,440,000 rows
Inserted 2,445,000 rows
Inserted 2,450,000 rows
Inserted 2,455,000 rows
Inserted 2,460,000 rows
Inserted 2,465,000 rows
Inserted 2,470,000 rows
Inserted 2,475,000 rows
Inserted 2,480,000 rows
Inserted 2,485,000 rows
Inserted 2,490,000 rows
Inserted 2,495,000 rows
Inserted 2,500,000 rows
Inserted 2,505,000 rows
Inserted 2,510,000 rows
Inserted 2,515,000 rows
Inserted 2,520,000 rows
Inserted 2,525,000 rows
Inserted 2,530,000 rows
Inserted 2,535,000 rows
Inserted 2,540,000 rows
Inserted 2,545,000 rows
Inserted 2,550,000 rows
Inserted 2,555,000 rows
Inserted 2,560,000 rows
Inserted 2,565,000 rows
Inserted 2,570,000 rows
Inserted 2,575,000 rows
Inserted 2,580,000 rows
Inserted 2,585,000 rows
Inserted 2,590,000 rows
Inserted 2,595,000 rows
Inserted 2,600,000 rows
Inserted 2,605,000 rows
Inserted 2,610,000 rows
Inserted 2,615,000 rows
Inserted 2,620,000 rows
Inserted 2,625,000 rows
Inserted 2,630,000 rows
Inserted 2,635,000 rows
Inserted 2,640,000 rows
Inserted 2,645,000 rows
Inserted 2,650,000 rows
Inserted 2,655,000 rows
Inserted 2,660,000 rows
Inserted 2,665,000 rows
Inserted 2,670,000 rows
Inserted 2,675,000 rows
Inserted 2,680,000 rows
Inserted 2,685,000 rows
Inserted 2,690,000 rows
Inserted 2,695,000 rows
Inserted 2,700,000 rows
Inserted 2,705,000 rows
Inserted 2,710,000 rows
Inserted 2,715,000 rows
Inserted 2,720,000 rows
Inserted 2,725,000 rows
Inserted 2,730,000 rows
Inserted 2,735,000 rows
Inserted 2,740,000 rows
Inserted 2,745,000 rows
Inserted 2,750,000 rows
Inserted 2,755,000 rows
Inserted 2,760,000 rows
Inserted 2,765,000 rows
Inserted 2,770,000 rows
Inserted 2,775,000 rows
Inserted 2,780,000 rows
Inserted 2,785,000 rows
Inserted 2,790,000 rows
Inserted 2,795,000 rows
Inserted 2,800,000 rows
Inserted 2,805,000 rows
Inserted 2,810,000 rows
Inserted 2,815,000 rows
Inserted 2,820,000 rows
Inserted 2,825,000 rows
Inserted 2,830,000 rows
Inserted 2,835,000 rows
Inserted 2,840,000 rows
Inserted 2,845,000 rows
Inserted 2,850,000 rows
Inserted 2,855,000 rows
Inserted 2,860,000 rows
Inserted 2,865,000 rows
Inserted 2,870,000 rows
Inserted 2,875,000 rows
Inserted 2,880,000 rows
Inserted 2,885,000 rows
Inserted 2,890,000 rows
Inserted 2,895,000 rows
Inserted 2,900,000 rows
Inserted 2,905,000 rows
Inserted 2,910,000 rows
Inserted 2,915,000 rows
Inserted 2,920,000 rows
Inserted 2,925,000 rows
Inserted 2,930,000 rows
Inserted 2,935,000 rows
Inserted 2,940,000 rows
Inserted 2,945,000 rows
Inserted 2,950,000 rows
Inserted 2,955,000 rows
Inserted 2,960,000 rows
Inserted 2,965,000 rows
Inserted 2,970,000 rows
Inserted 2,975,000 rows
Inserted 2,980,000 rows
Inserted 2,985,000 rows
Inserted 2,990,000 rows
Inserted 2,995,000 rows
Inserted 3,000,000 rows
Inserted 3,005,000 rows
Inserted 3,010,000 rows
Inserted 3,015,000 rows
Inserted 3,020,000 rows
Inserted 3,025,000 rows
Inserted 3,030,000 rows
Inserted 3,035,000 rows
Inserted 3,040,000 rows
Inserted 3,045,000 rows
Inserted 3,050,000 rows
Inserted 3,055,000 rows
Inserted 3,060,000 rows
Inserted 3,065,000 rows
Inserted 3,070,000 rows
Inserted 3,075,000 rows
Inserted 3,080,000 rows
Inserted 3,085,000 rows
Inserted 3,090,000 rows
Inserted 3,095,000 rows
Inserted 3,100,000 rows
Inserted 3,105,000 rows
Inserted 3,110,000 rows
Inserted 3,115,000 rows
Inserted 3,120,000 rows
Inserted 3,125,000 rows
Inserted 3,130,000 rows
Inserted 3,135,000 rows
Inserted 3,140,000 rows
Inserted 3,145,000 rows
Inserted 3,150,000 rows
Inserted 3,155,000 rows
Inserted 3,160,000 rows
Inserted 3,165,000 rows
Inserted 3,170,000 rows
Inserted 3,175,000 rows
Inserted 3,180,000 rows
Inserted 3,185,000 rows
Inserted 3,190,000 rows
Inserted 3,195,000 rows
Inserted 3,200,000 rows
Inserted 3,205,000 rows
Inserted 3,210,000 rows
Inserted 3,215,000 rows
Inserted 3,220,000 rows
Inserted 3,225,000 rows
Inserted 3,230,000 rows
Inserted 3,235,000 rows
Inserted 3,240,000 rows
Inserted 3,245,000 rows
Inserted 3,250,000 rows
Inserted 3,255,000 rows
Inserted 3,260,000 rows
Inserted 3,265,000 rows
Inserted 3,270,000 rows
Inserted 3,275,000 rows
Inserted 3,280,000 rows
Inserted 3,285,000 rows
Inserted 3,290,000 rows
Inserted 3,295,000 rows
Inserted 3,300,000 rows
Inserted 3,305,000 rows
Inserted 3,310,000 rows
Inserted 3,315,000 rows
Inserted 3,320,000 rows
Inserted 3,325,000 rows
Inserted 3,330,000 rows
Inserted 3,335,000 rows
Inserted 3,340,000 rows
Inserted 3,345,000 rows
Inserted 3,350,000 rows
Inserted 3,355,000 rows
Inserted 3,360,000 rows
Inserted 3,365,000 rows
Inserted 3,370,000 rows
Inserted 3,375,000 rows
Inserted 3,380,000 rows
Inserted 3,385,000 rows
Inserted 3,390,000 rows
Inserted 3,395,000 rows
Inserted 3,400,000 rows
Inserted 3,405,000 rows
Inserted 3,410,000 rows
Inserted 3,415,000 rows
Inserted 3,420,000 rows
Inserted 3,425,000 rows
Inserted 3,430,000 rows
Inserted 3,435,000 rows
Inserted 3,440,000 rows
Inserted 3,445,000 rows
Inserted 3,450,000 rows
Inserted 3,455,000 rows
Inserted 3,460,000 rows
Inserted 3,465,000 rows
Inserted 3,470,000 rows
Inserted 3,475,000 rows
Inserted 3,480,000 rows
Inserted 3,485,000 rows
Inserted 3,490,000 rows
Inserted 3,495,000 rows
Inserted 3,500,000 rows
Inserted 3,505,000 rows
Inserted 3,510,000 rows
Inserted 3,515,000 rows
Inserted 3,520,000 rows
Inserted 3,525,000 rows
Inserted 3,530,000 rows
Inserted 3,535,000 rows
Inserted 3,540,000 rows
Inserted 3,545,000 rows
Inserted 3,550,000 rows
Inserted 3,555,000 rows
Inserted 3,560,000 rows
Inserted 3,565,000 rows
Inserted 3,570,000 rows
Inserted 3,575,000 rows
Inserted 3,580,000 rows
Inserted 3,585,000 rows
Inserted 3,590,000 rows
Inserted 3,595,000 rows
Inserted 3,600,000 rows
Inserted 3,605,000 rows
Inserted 3,610,000 rows
Inserted 3,615,000 rows
Inserted 3,620,000 rows
Inserted 3,625,000 rows
Inserted 3,630,000 rows
Inserted 3,635,000 rows
Inserted 3,640,000 rows
Inserted 3,645,000 rows
Inserted 3,650,000 rows
Inserted 3,655,000 rows
Inserted 3,660,000 rows
Inserted 3,665,000 rows
Inserted 3,670,000 rows
Inserted 3,675,000 rows
Inserted 3,680,000 rows
Inserted 3,685,000 rows
Inserted 3,690,000 rows
Inserted 3,695,000 rows
Inserted 3,700,000 rows
Inserted 3,705,000 rows
Inserted 3,710,000 rows
Inserted 3,715,000 rows
Inserted 3,720,000 rows
Inserted 3,725,000 rows
Inserted 3,730,000 rows
Inserted 3,735,000 rows
Inserted 3,740,000 rows
Inserted 3,745,000 rows
Inserted 3,750,000 rows
Inserted 3,755,000 rows
Inserted 3,760,000 rows
Inserted 3,765,000 rows
Inserted 3,770,000 rows
Inserted 3,775,000 rows
Inserted 3,780,000 rows
Inserted 3,785,000 rows
Inserted 3,790,000 rows
Inserted 3,795,000 rows
Inserted 3,800,000 rows
Inserted 3,805,000 rows
Inserted 3,810,000 rows
Inserted 3,815,000 rows
Inserted 3,820,000 rows
Inserted 3,825,000 rows
Inserted 3,830,000 rows
Inserted 3,835,000 rows
Inserted 3,840,000 rows
Inserted 3,845,000 rows
Inserted 3,850,000 rows
Inserted 3,855,000 rows
Inserted 3,860,000 rows
Inserted 3,865,000 rows
Inserted 3,870,000 rows
Inserted 3,875,000 rows
Inserted 3,880,000 rows
Inserted 3,885,000 rows
Inserted 3,890,000 rows
Inserted 3,895,000 rows
Inserted 3,900,000 rows
Inserted 3,905,000 rows
Inserted 3,910,000 rows
Inserted 3,915,000 rows
Inserted 3,920,000 rows
Inserted 3,925,000 rows
Inserted 3,930,000 rows
Inserted 3,935,000 rows
Inserted 3,940,000 rows
Inserted 3,945,000 rows
Inserted 3,950,000 rows
Inserted 3,955,000 rows
Inserted 3,960,000 rows
Inserted 3,965,000 rows
Inserted 3,970,000 rows
Inserted 3,975,000 rows
Inserted 3,980,000 rows
Inserted 3,985,000 rows
Inserted 3,990,000 rows
Inserted 3,995,000 rows
Inserted 4,000,000 rows
Inserted 4,005,000 rows
Inserted 4,010,000 rows
Inserted 4,015,000 rows
Inserted 4,020,000 rows
Inserted 4,025,000 rows
Inserted 4,030,000 rows
Inserted 4,035,000 rows
Inserted 4,040,000 rows
Inserted 4,045,000 rows
Inserted 4,050,000 rows
Inserted 4,055,000 rows
Inserted 4,060,000 rows
Inserted 4,065,000 rows
Inserted 4,070,000 rows
Inserted 4,075,000 rows
Inserted 4,080,000 rows
Inserted 4,085,000 rows
Inserted 4,090,000 rows
Inserted 4,095,000 rows
Inserted 4,100,000 rows
Inserted 4,105,000 rows
Inserted 4,110,000 rows
Inserted 4,115,000 rows
Inserted 4,120,000 rows
Inserted 4,125,000 rows
Inserted 4,130,000 rows
Inserted 4,135,000 rows
Inserted 4,140,000 rows
Inserted 4,145,000 rows
Inserted 4,150,000 rows
Inserted 4,155,000 rows
Inserted 4,160,000 rows
Inserted 4,165,000 rows
Inserted 4,170,000 rows
Inserted 4,175,000 rows
Inserted 4,180,000 rows
Inserted 4,185,000 rows
Inserted 4,190,000 rows
Inserted 4,195,000 rows
Inserted 4,200,000 rows
Inserted 4,205,000 rows
Inserted 4,210,000 rows
Inserted 4,215,000 rows
Inserted 4,220,000 rows
Inserted 4,225,000 rows
Inserted 4,230,000 rows
Inserted 4,235,000 rows
Inserted 4,240,000 rows
Inserted 4,245,000 rows
Inserted 4,250,000 rows

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)